# Generated by Django 4.0.6 on 2022-08-02 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_pin', models.PositiveBigIntegerField()),
                ('account_balance', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_and_agent_rating', models.CharField(max_length=20)),
                ('transcript_emails', models.CharField(max_length=100)),
                ('chat_log', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('adress', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('customergender', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('repayment_reschedules', models.DateTimeField(default=datetime.datetime.now)),
                ('loan_id', models.CharField(max_length=20)),
                ('loan_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('message', models.CharField(max_length=100)),
                ('transaction_description', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_amount', models.PositiveBigIntegerField()),
                ('transaction_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qr_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('contact_details', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=100)),
                ('receipt_date', models.DateField()),
                ('bill_number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('customer_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_number', models.PositiveBigIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField()),
                ('user_id', models.PositiveBigIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=100)),
                ('history', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Card_number', models.IntegerField()),
                ('pin', models.CharField(max_length=20)),
                ('debit_card', models.CharField(max_length=20)),
                ('credit_card', models.CharField(max_length=20)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('issued_date', models.DateTimeField(default=datetime.datetime.now)),
                ('issuer', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_Code', models.CharField(max_length=20)),
                ('transaction_number', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.receipt')),
                ('destination_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination_account', to='wallet.account')),
                ('origin_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_origin_account', to='wallet.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
