# Generated by Django 4.0.6 on 2022-08-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_pin', models.PositiveBigIntegerField()),
                ('account_balance', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_and_agent_rating', models.CharField(max_length=20)),
                ('transcript_emails', models.CharField(max_length=100)),
                ('chat_log', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('period_of_loan', models.DateTimeField()),
                ('repayment_reschedules', models.DateTimeField()),
                ('loan_id', models.CharField(max_length=20)),
                ('loan_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('transaction_description', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_amount', models.PositiveBigIntegerField(max_length=20)),
                ('transaction_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qr_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('contact_details', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=100)),
                ('receipt_date', models.DateField()),
                ('bill_number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('customer_id', models.PositiveBigIntegerField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_number', models.PositiveBigIntegerField()),
                ('amount', models.PositiveBigIntegerField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField()),
                ('user_id', models.PositiveBigIntegerField(max_length=20)),
                ('amount', models.PositiveBigIntegerField(max_length=20)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('history', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture/'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Card_number', models.IntegerField()),
                ('pin', models.CharField(max_length=20)),
                ('debit_card', models.CharField(max_length=20)),
                ('credit_card', models.CharField(max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('issued_date', models.DateTimeField()),
                ('issuer', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_Code', models.CharField(max_length=20)),
                ('transaction_number', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=20)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.receipt')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination_account', to='wallet.account')),
                ('wallet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
