# Generated by Django 4.0.6 on 2022-08-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_chatbot_currency_loan_notifications_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
