# Generated by Django 4.0.6 on 2022-10-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
