# Generated by Django 4.0.6 on 2022-08-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_origin_account_alter_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Gender',
        ),
    ]
