# Generated by Django 4.0.6 on 2022-10-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_customer_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress',
            new_name='address',
        ),
    ]
