# Generated by Django 4.0.6 on 2022-08-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_customer_gender_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Gender',
            new_name='gender',
        ),
    ]
